repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.2
  hooks:
  - id: ruff
  - id: ruff-format
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
- repo: local
  hooks:
    - id: ty-check
      name: ty-check
      language: python
      entry: ty check
      pass_filenames: false
      additional_dependencies: [ty]
